/*

https://projecteuler.net/problem=2

Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Paul Merrigan, 7/21/2016

*/
var x = 1;
var y = 2;
var z = 0;
var sum = y; // 2 is even, so start summing there

while (z < 4000000) {

    z = (x + y);

    if (z % 2 === 0) {

        sum += z;
    }
    x = y;
    y = z;
}

console.log(sum);